spring.application.name=siteAmame

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port par default
server.port=${PORT:8080}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

file.storage.upload-dir=uploads/

# Configuration de la taille maximale des fichiers uploades
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true
#Cle Secrete
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Url Frontend
frontend=${FRONTEND}

# Indispensable pour que Spring sache quil est derriere un proxy HTTPS
server.forward-headers-strategy=framework