#spring.application.name=siteAmame
#
#spring.datasource.url=jdbc:postgresql://database:5432/amame_db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Port par default
#server.port=${PORT:8080}
#
#logging.level.org.springframework.web=INFO
#logging.level.org.springframework.security=INFO
#
#file.storage.upload-dir=uploads/
#
## Configuration de la taille maximale des fichiers uploades
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=5MB
#spring.servlet.multipart.enabled=true
##Cle Secrete
#jwt.secret=${JWT_SECRET}
#jwt.expiration=${JWT_EXPIRATION}
#
##Url Frontend
#frontend=${FRONTEND}
#
## Indispensable pour que Spring sache quil est derriere un proxy HTTPS
#server.forward-headers-strategy=framework
#
#server.compression.enabled=true
#server.compression.mime-types=application/json,text/html,text/xml,text/plain,text/css,application/javascript
#server.compression.min-response-size=1024


# Configuration de base
spring.application.name=siteAmame

# Profil actif (a definir via variable denvironnement)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Configuration commune a tous les environnements
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# Compression (utile partout)
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,text/css,application/javascript
server.compression.min-response-size=1024

# Upload de fichiers (limites communes)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true

# Dossier de stockage
file.storage.upload-dir=uploads/
